### ISSUE TITLE
Missing FusionLauncher.exe.ini after install

### ISSUE THREAD

**Issue by arsenixprime** [Thermionix/fusion360#30]
I am getting an error after install that is blocking launch. "Configuration file FusionLauncher.exe.ini is missing or incomplete".

There is a note about this on the autodesk site: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Error-Configuration-file-Fusion-Launcher-exe-ini-is-missing-or-incomplete-when-launching-Fusion-360.html

They recommend "resetting" fusion360 using the service utility. 

![2024-03-29_09-09](https://github.com/Thermionix/fusion360/assets/8421872/7276caa6-2dac-49ca-9e1b-4f8d46dc40f5)

Any ideas?

Appreciate the work on this project!

**Comment by Ghostbird** [comment]
I've encountered the same problem. Reinstalling the application didn't work, the same error reoccurred.

**Comment by lucaci32u4** [comment]
I am having the same issue. Edge also shows an error during installation like in !29. 
Reinstalling does not fix the issue.

**Comment by johnnytolengo** [comment]
the same issue here
![image](https://github.com/Thermionix/fusion360/assets/5218298/7b8f54f6-a969-47d2-bed3-1c67ee0a5abe)

**Comment by androuino** [comment]
the same error here.

My os info from `lsb_release -a` command

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

**Comment by virgilHirtz** [comment]
Received the same error.

**Comment by stolmen** [comment]
Yup same error here

```
ed@fedora:~$ lsb_release -a
LSB Version:	n/a
Distributor ID:	Fedora
Description:	Fedora Linux 39 (Workstation Edition)
Release:	39
Codename:	n/a
ed@fedora:~$ uname -a
Linux fedora 6.7.10-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 18 18:56:52 UTC 2024 x86_64 GNU/Linux

```

**Comment by GWXerxes** [comment]
Having the same issue as well. Ubuntu 23.10

FusionLauncher.exe.ini error as well as Edge errors during install. The contents of the FusionLauncher.exe.ini file are as follows

`This is a place-holder file which is intended to be updated by the streamer.`

I'll attempt troubleshooting when I can, but I wanted to add to the list of people experiencing the issue

**Comment by arsenixprime** [comment]
This issue is discussed here at length: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/408

The install is not completing and Fusion360.exe is being deleted during the installation. Apparently this is due to a "rebranding function" that renames all "Fusion 360" shortcuts to just "Fusion".

The poster made a hacky script that monitors the log and kills streamer.exe as soon as it starts this process, leaving the app still intact enough to run.

Trying to see if I can get that same technique to work.

**Comment by arsenixprime** [comment]
I managed I believe get the script to run but it doesn't appear to have worked. The damage seems like it was already done despite killing streamer.exe

**Comment by arsenixprime** [comment]
It seems like the "renaming process" mentioned on that thread may be completing properly but whatever happens immediately after gets an exception and fails. I'm not finding anything looking around online for similar errors. This is the relevant excerpt from the log:
`2024-04-14 22:27:37,465 - MainProcess(296) - ThreadPoolExecutor-1_0 - adsk.dls.streamer.windows.platform - INFO :: original launch icon: C:\Program Files\Autodesk\webdeploy\production\6a0c961
2024-04-14 22:27:37,465 - MainProcess(296) - ThreadPoolExecutor-1_0 - adsk.dls.streamer.windows.platform - INFO :: new launch icon: C:\Program Files\Autodesk\webdeploy\production\6a0c9611291d
2024-04-14 22:27:37,509 - MainProcess(296) - ThreadPoolExecutor-1_0 - adsk.dls.streamer.windows.platform - INFO :: original name: Autodesk Fusion
2024-04-14 22:27:37,510 - MainProcess(296) - ThreadPoolExecutor-1_0 - adsk.dls.streamer.windows.platform - INFO :: stream name: production
2024-04-14 22:27:37,510 - MainProcess(296) - ThreadPoolExecutor-1_0 - adsk.dls.streamer.windows.platform - INFO :: new name: Autodesk Fusion
2024-04-14 22:27:37,511 - MainProcess(296) - ThreadPoolExecutor-1_0 - adsk.dls.streamer.process.process - WARNING :: Exception processing tasks for 99fa7380261aad1710f7cd69c74ba4edd588af50: [
2024-04-14 22:27:37,599 - MainProcess(296) - MainThread - adsk.dls.streamer.process.process - INFO :: The host autodesk.com is accessible
2024-04-14 22:27:37,656 - MainProcess(296) - MainThread - adsk.dls.streamer.process.process - INFO :: S_I: NTAuMTkuMTQ5LjQ=
2024-04-14 22:27:37,657 - MainProcess(296) - MainThread - adsk.dls.streamer.process.process - INFO :: C_PR_I: MTI3LjAuMS4x
2024-04-14 22:27:37,678 - MainProcess(296) - MainThread - adsk.dls.streamer.network_checker - WARNING :: Failed to get local dns [WinError 2] File not found.
2024-04-14 22:27:37,679 - MainProcess(296) - MainThread - adsk.dls.streamer.process.process - INFO :: Local DNS:
2024-04-14 22:27:37,680 - MainProcess(296) - MainThread - adsk.dls.streamer.process.process - INFO :: Detected proxies: e30=
2024-04-14 22:27:37,681 - MainProcess(296) - MainThread - adsk.dls.streamer.process.process - ERROR :: Exception during processing:
Traceback (most recent call last):
  File "R:\src\adsk\dls\streamer\process\process.py", line 1190, in execute
  File "R:\src\adsk\dls\streamer\process\deploy_process.py", line 95, in execute_without_errorhandling
  File "R:\src\adsk\dls\streamer\process\process.py", line 1120, in execute_without_errorhandling
  File "R:\src\adsk\dls\streamer\process\process.py", line 932, in _config_app
  File "R:\src\adsk\dls\streamer\process\process.py", line 1932, in _do_installation
  File "R:\src\adsk\dls\streamer\process\process.py", line 1693, in wait_threads
  File "D:\Jenkins\3P\PYTHON\3.11.1\WIN64_1\Lib\concurrent\futures\thread.py", line 58, in run
  File "R:\src\adsk\dls\streamer\process\process.py", line 1813, in execute_tasks
  File "R:\src\adsk\dls\streamer\process\process.py", line 415, in _executetasks
  File "R:\src\adsk\dls\streamer\windows\platform.py", line 371, in create_launch_items
  File "R:\src\adsk\dls\streamer\windows\platform.py", line 541, in _manipulate_shortcuts
  File "R:\src\adsk\dls\streamer\manifests.py", line 807, in walk_external_references
  File "R:\src\adsk\dls\streamer\windows\platform.py", line 476, in __filevisitor
  File "R:\src\adsk\dls\streamer\windows\platform.py", line 197, in _rebrand_shortcut
  File "R:\src\adsk\dls\streamer\windows\platform.py", line 191, in _get_destination
  File "D:\Jenkins\3P\PYTHON\3.11.1\WIN64_1\Lib\re\__init__.py", line 185, in sub
  File "R:\src\adsk\dls\streamer\windows\platform.py", line 188, in __map
  File "R:\src\adsk\dls\streamer\windows\native.py", line 497, in GetKnownFolderPath
  File "R:\src\adsk\dls\streamer\windows\native.py", line 761, in GetKnownFolderPath
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -2147024809] Invalid parameter`

**Comment by cvanelteren** [comment]
same issue here

**Comment by FirstForest20** [comment]
Same issue here. Fingers crossed for resolving it soon

**Comment by Thermionix** [comment]
fusion360 installer currently failing due to [wine issue](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/408), I've pushed a [merge request to winehq](https://gitlab.winehq.org/wine/wine/-/merge_requests/5525)

**Comment by GerritVK** [comment]
Looks like this has been merged in. Are there changes to this repo needed to use the new version?

**Comment by Thermionix** [comment]
Just awaiting wine-9.8 release binaries

**Comment by stylesuxx** [comment]
Just a heads up: wine-9.8 binaries are available since yesterday if I understand correctly.

**Comment by Thermionix** [comment]
![Screenshot_20240505_115516](https://github.com/Thermionix/fusion360/assets/622615/b724e554-2903-4769-b9b4-8f6e3a1bcdb9)

Updated repo, tested locally with Firefox, callback to adskidmgr-opener working

**Comment by Thermionix** [comment]
Attempting to solve `ERROR: You need to connect this snap to the wine runtime snap.` 
snap connections on the published snap via [Interface auto-connection mechanism](https://snapcraft.io/docs/auto-connection-mechanism)

**Comment by Thermionix** [comment]
[auto-connection-request-for-wine-platform-9-stable-devel-staging-snaps](https://forum.snapcraft.io/t/auto-connection-request-for-wine-platform-9-stable-devel-staging-snaps/40063)

**Comment by Thermionix** [comment]
Ok, updated setup instructions whilst awaiting for global auto connection;
````
$ sudo snap install --edge fusion360 --devmode
sudo snap connect fusion360:wine-9-devel wine-platform-9-devel-core22
sudo snap connect fusion360:wine-runtime-c22 wine-platform-runtime-core22
fusion360
````

**Comment by johnnytolengo** [comment]
@Thermionix  your recipe worked on my Ubuntu 22.04 with "apt install --install-recommends winehq-devel"
Thanks!

**Comment by mrkrynmdsco** [comment]
> Ok, updated setup instructions whilst awaiting for global auto connection;
> 
> ```
> $ sudo snap install --edge fusion360 --devmode
> sudo snap connect fusion360:wine-9-devel wine-platform-9-devel-core22
> sudo snap connect fusion360:wine-runtime-c22 wine-platform-runtime-core22
> fusion360
> ```

hi,
after signing in it does not seem to re-direct properly and cannot locate the app.
![image](https://github.com/Thermionix/fusion360/assets/11093642/34b4b352-0caf-4661-9fb4-6c322b01d5ab)

**Comment by Thermionix** [comment]
so the [post-install](https://github.com/Thermionix/fusion360/blob/main/hooks/post-install) script sets this up, 

can you check the output of
 `cat ~/.local/share/applications/adskidmgr-opener.desktop`

e.g. mine:
````
$ cat ~/.local/share/applications/adskidmgr-opener.desktop
[Desktop Entry]
Type=Application
Name=adskidmgr Scheme Handler
Exec=sh -c 'fusion360.wine "$(find /home/thermionix/snap/fusion360/common/.wine -name "AdskIdentityManager.exe" | head -1 | xargs -I '{}' echo {})" "%u"'
StartupNotify=false
MimeType=x-scheme-handler/adskidmgr;
````

The line `xdg-mime default adskidmgr-opener.desktop x-scheme-handler/adskidmgr` registers this as the default handler. This is the second area which may have not worked

**Comment by Thermionix** [comment]
and check output of
`xdg-mime query default x-scheme-handler/adskidmgr`

````
$ xdg-mime query default x-scheme-handler/adskidmgr
adskidmgr-opener.desktop
````

**Comment by dotvezz** [comment]
I'm seeing the same behavior as @mrkrynmdsco after logging in on my browser (With the same browser, Firefox).

```
 > xdg-mime query default x-scheme-handler/adskidmgr
adskidmgr-opener.desktop
 > cat ~/.local/share/applications/adskidmgr-opener.desktop
[Desktop Entry]
Type=Application
Name=adskidmgr Scheme Handler
Exec=sh -c 'fusion360.wine "$(find /home/ben/snap/fusion360/common/.wine -name "AdskIdentityManager.exe" | head -1 | xargs -I '{}' echo {})" "%u"'
StartupNotify=false
MimeType=x-scheme-handler/adskidmgr;
```

**Comment by Thermionix** [comment]
can you please try this & relaunch firefox:
````
update-mime-database ~/.local/share/mime/
XDG_UTILS_DEBUG_LEVEL=2 xdg-mime query default x-scheme-handler/adskidmgr
````

**Comment by dotvezz** [comment]
Sadly no dice.

```
 > update-mime-database ~/.local/share/mime/
   XDG_UTILS_DEBUG_LEVEL=2 xdg-mime query default x-scheme-handler/adskidmgr
Directory '/home/ben/.local/share/mime/packages' does not exist!
Checking /home/ben/.config/mimeapps.list
Checking /home/ben/.local/share/applications/mimeapps.list
Checking /usr/share/applications/kde-mimeapps.list
Checking /home/ben/.local/share/applications/plasma-defaults.list and /home/ben/.local/share/applications/plasma-mimeinfo.cache
Checking /home/ben/.local/share/applications/defaults.list and /home/ben/.local/share/applications/mimeinfo.cache
Checking /home/ben/.local/share/flatpak/exports/share/applications/plasma-defaults.list and /home/ben/.local/share/flatpak/exports/share/applications/plasma-mimeinfo.cache
Checking /home/ben/.local/share/flatpak/exports/share/applications/defaults.list and /home/ben/.local/share/flatpak/exports/share/applications/mimeinfo.cache
Checking /var/lib/flatpak/exports/share/applications/plasma-defaults.list and /var/lib/flatpak/exports/share/applications/plasma-mimeinfo.cache
Checking /var/lib/flatpak/exports/share/applications/defaults.list and /var/lib/flatpak/exports/share/applications/mimeinfo.cache
Checking /usr/local/share/applications/plasma-defaults.list and /usr/local/share/applications/plasma-mimeinfo.cache
Checking /usr/local/share/applications/defaults.list and /usr/local/share/applications/mimeinfo.cache
Checking /usr/share/applications/plasma-defaults.list and /usr/share/applications/plasma-mimeinfo.cache
Checking /usr/share/applications/defaults.list and /usr/share/applications/mimeinfo.cache
Checking /var/lib/snapd/desktop/applications/plasma-defaults.list and /var/lib/snapd/desktop/applications/plasma-mimeinfo.cache
Checking /var/lib/snapd/desktop/applications/defaults.list and /var/lib/snapd/desktop/applications/mimeinfo.cache
 Checking /home/ben/.local/share/applications/adskidmgr-opener.desktop
   Select /home/ben/.local/share/applications/adskidmgr-opener.desktop [ -1 => 0 ]
adskidmgr-opener.desktop
 > pkill firefox
 ```

Tried again and got the same behavior.

**Comment by Thermionix** [comment]
I can't remember what I did the first time the askidmgr scheme prompted, but I believe I clicked something along the lines of allow content type 'askidmgr' and now within firefox:
![image](https://github.com/Thermionix/fusion360/assets/622615/5ab05638-2703-4c6b-bf5f-5db5d4b9bf48)

The issue maybe [firefox ignoring](https://bugzilla.mozilla.org/show_bug.cgi?id=1580686) `~/.config/mimeapps.list`

**Comment by Thermionix** [comment]
From the [ArchWiki - XDG_MIME_Applications](https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list) - 
`~/.local/share/applications/mimeapps.list` is **deprecated** (which firefox is reading)
and the solution is:
`$ ln -s ~/.config/mimeapps.list ~/.local/share/applications/mimeapps.list`

**Comment by eruanno123** [comment]
I tried this solution with symbolic link and the redirection seems to work fine now.

Meanwhile, I see a lot of ERROR messages, that did not appear earlier.

```
ERROR: ld.so: object '/snap/fusion360/32/gnome-platform/$LIB/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

This seems to be not an issue though for running the application.

**Comment by stylesuxx** [comment]
Firefox does not not prompt me at all after login. Chrome does prompt me, but the redirect simply does nothing, even not after hitting retry or symlinking the files. Is there any way the URL can be passed manually without the whole redirect mechanic?

**Comment by smirgol** [comment]
For me the redirect was also not working. What did work in the end was copying the redirect link from the browser login and executing what the `.desktop` file is supposed to do manually in the shell:

`fusion360.wine "/home/myuser/snap/fusion360/common/.wine/drive_c/Program Files/Autodesk/webdeploy/production/35a60349b112668a59dd7bbcc68b2622875103f4/Autodesk Identity Manager/AdskIdentityManager.exe" "adskidmgr:/login?code=asdasdfsdfsdfsfsfsfsdffsdfsdfsfd="`

Obviously replace `adskidmgr:/login?code=asdasdfsdfsdfsfsfsfsdffsdfsdfsfd=` with the link from the login in the browser and fetch the correct path to `AdskIdentManager.exe` with:
`find ~/snap/fusion360/common/.wine -name "AdskIdentityManager.exe" | head -1 | xargs -I '{}' echo {}`

**Comment by stylesuxx** [comment]
@smirgol - thank you, this actually did work! Unfortunately fusion itself is absolutely unusable. I guess I'll come back in a couple of years again and see if they could be bothered to roll out proper Linux support.

@Thermionix thank you for your hard work on this project.

**Comment by smirgol** [comment]
Yeah fusion itself is a mess, always has been. While it now starts for me, I cannot save projects nor export any meshes, which renders it useless (again). *sighs*
